# Chain Matrix Multiplication Optimal Sequence

In [ ]:
!python -m pip install numpy

In [7]:
import math
import numpy as np

n = 4
b = [200, 2, 30, 20, 5]
m = np.zeros((n+1, n+1))
s = np.zeros((n+1, n+1))

def minMultRec(b, i, j):
    if i == j:
        m[i][j] = 0
    else:
        m[i][j] = math.inf
        for k in range(i, j):
            q = minMultRec(b, i, k) + minMultRec(b, k+1, j) + b[i - 1] * b[k] * b[j]
            if m[i][j] > q:
                m[i][j] = q
                s[i][j] = k

    return m[i][j]

print(minMultRec(b, 1, n))
print(m)
print(s)

3400.0
[[    0.     0.     0.     0.     0.]
 [    0.     0. 12000.  9200.  3400.]
 [    0.     0.     0.  1200.  1400.]
 [    0.     0.     0.     0.  3000.]
 [    0.     0.     0.     0.     0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 2. 3.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]]


In [13]:
def matmul(M, s, i, j):
    if i == j:
        return i
    else:
        X = matmul(M, s, i, s[i, j])
        Y = matmul(M, s, s[i,j] + 1, j)
        print(X, Y, b[i - 1], b[s[i, j]], b[j])

s = s.astype(np.int64)
matmul([1, 2, 3, 4], s, 1, n)

2 3 2 30 20
None 4 2 20 5
1 None 200 2 5
