<a href="https://colab.research.google.com/github/pcsilcan/ca/blob/master/20202/ca_20202_0102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import random as rnd
import numpy as np
import math

In [6]:
print([0 for _ in range(10)])
print([i for i in range(10)])
print([i*i for i in range(10)])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [2]:
def generate(n):
    return [rnd.randint(1, 100) for _ in range(n)]

In [3]:
generate(10)

[44, 74, 31, 41, 38, 76, 83, 53, 46, 85]

In [10]:
print([0]*5)

[0, 0, 0, 0, 0]


In [7]:
def freq(t):
    n = len(t)
    m = max(t)
    s = [0]*(m+1)

    for e in t:
        s[e] += 1

    return s

In [8]:
freq([rnd.randint(1, 20) for _ in range(1000)])

[0,
 58,
 48,
 54,
 40,
 47,
 35,
 59,
 38,
 56,
 52,
 45,
 62,
 43,
 55,
 60,
 50,
 58,
 58,
 55,
 27]

In [11]:
print([i for i in range(100)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [17]:
a = [i*i for i in range(20)]
print(a)
print(a[:])
print(a[10:])
print(a[:10])
print(a[6:15])

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
[100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[36, 49, 64, 81, 100, 121, 144, 169, 196]


In [36]:
def checkSudoku(t):
    n = len(t)
    tab = np.array(t)

    for i in range(n):
        row = set(tab[i])
        if len(row) < n:
            return False

        column = set(tab[:, i])
        if len(column) < n:
            return False

    m = int(math.sqrt(n))
    for i in range(m):
        for j in range(m):
            block = set(tab[i*m:(i+1)*m,j*m:(j+1)*m].reshape((n)))
            if len(block) < n:
                return False

    return True

In [37]:
t = [[1, 2, 3, 4],
     [3, 4, 1, 2],
     [2, 3, 4, 1],
     [4, 2, 2, 3]]
print(checkSudoku(t))

False


In [45]:
tab = np.array(t)
print(tab)
print(tab[2])
print(tab[:, 3])
print(tab[1:3,2:4])
print(tab[1:3,2:4].shape)
print(tab[1:3,2:4].reshape((4)))
print(tab.shape)

[[1 2 3 4]
 [3 4 1 2]
 [2 3 4 1]
 [4 2 2 3]]
[2 3 4 1]
[4 2 1 3]
[[1 2]
 [4 1]]
(2, 2)
[1 2 4 1]
(4, 4)
