<a href="https://colab.research.google.com/github/pcsilcan/ca/blob/master/20202/ca_20202_131_floyd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Floyd Warshall

In [1]:
import math

In [7]:
def initMultpleSource(G):
    n = len(G)
    dist = [[math.inf if i!=j and G[i][j] == 0
             else G[i][j] 
             for j in range(n)]
            for i in range(n)]
    path = [[-1 if G[i][j] == 0
             else i
             for j in range(n)]
            for i in range(n)]
    return dist, path

In [3]:
def relax(i, k, j, dist, path):
    W = dist[i][k] + dist[k][j]
    if dist[i][j] > W:
        dist[i][j] = W
        path[i][j] = path[k][j]        

In [4]:
def floydWarshall(G):
    n = len(G)
    dist, path = initMultpleSource(G)
    for k in range(n):
        for i in range(n):
            for j in range(n):
                if i != k and k != j and j != i:
                    relax(i, k, j, dist, path)

    return dist, path

In [5]:
G = [[ 0,  3,  8,  0, -4],
     [ 0,  0,  0,  1,  7],
     [ 0,  4,  0,  0,  0],
     [ 2,  0, -5,  0,  0],
     [ 0,  0,  0,  6,  0]]

In [8]:
import numpy as np

d, p = floydWarshall(G)
print(np.array(d))
print(np.array(p))

[[ 0  1 -3  2 -4]
 [ 3  0 -4  1 -1]
 [ 7  4  0  5  3]
 [ 2 -1 -5  0 -2]
 [ 8  5  1  6  0]]
[[-1  2  3  4  0]
 [ 3 -1  3  1  0]
 [ 3  2 -1  1  0]
 [ 3  2  3 -1  0]
 [ 3  2  3  4 -1]]
